// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.1
// source: upstream.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 上游请求消息
type UpstreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                                      // 会话ID
	Openid        string                 `protobuf:"bytes,2,opt,name=openid,proto3" json:"openid,omitempty"`                                                                             // (新增) 用户的唯一标识
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`                                                                             // 操作类型
	Params        map[string]string      `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`   // 参数
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`                                                                                 // 原始数据
	Headers       map[string]string      `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 请求头
	ClientSeqId   uint64                 `protobuf:"varint,7,opt,name=client_seq_id,json=clientSeqId,proto3" json:"client_seq_id,omitempty"`                                             // 客户端序列号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamRequest) Reset() {
	*x = UpstreamRequest{}
	mi := &file_upstream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamRequest) ProtoMessage() {}

func (x *UpstreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upstream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamRequest.ProtoReflect.Descriptor instead.
func (*UpstreamRequest) Descriptor() ([]byte, []int) {
	return file_upstream_proto_rawDescGZIP(), []int{0}
}

func (x *UpstreamRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UpstreamRequest) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *UpstreamRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *UpstreamRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *UpstreamRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpstreamRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *UpstreamRequest) GetClientSeqId() uint64 {
	if x != nil {
		return x.ClientSeqId
	}
	return 0
}

// 上游响应消息
type UpstreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                                                                // 响应码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                                                           // 响应消息
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                                                                                 // 响应数据
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 响应头
	ClientSeqId   uint64                 `protobuf:"varint,5,opt,name=client_seq_id,json=clientSeqId,proto3" json:"client_seq_id,omitempty"`                                             // 对应的客户端序列号
	ServerSeqId   uint64                 `protobuf:"varint,6,opt,name=server_seq_id,json=serverSeqId,proto3" json:"server_seq_id,omitempty"`                                             // 上游服务生成的序列号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamResponse) Reset() {
	*x = UpstreamResponse{}
	mi := &file_upstream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamResponse) ProtoMessage() {}

func (x *UpstreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_upstream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamResponse.ProtoReflect.Descriptor instead.
func (*UpstreamResponse) Descriptor() ([]byte, []int) {
	return file_upstream_proto_rawDescGZIP(), []int{1}
}

func (x *UpstreamResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpstreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpstreamResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpstreamResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *UpstreamResponse) GetClientSeqId() uint64 {
	if x != nil {
		return x.ClientSeqId
	}
	return 0
}

func (x *UpstreamResponse) GetServerSeqId() uint64 {
	if x != nil {
		return x.ServerSeqId
	}
	return 0
}

// 状态请求消息
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // 服务名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_upstream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upstream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_upstream_proto_rawDescGZIP(), []int{2}
}

func (x *StatusRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

// 状态响应消息
type StatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Status            string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                                                               // 服务状态
	Uptime            int64                  `protobuf:"varint,2,opt,name=uptime,proto3" json:"uptime,omitempty"`                                                                              // 运行时间（秒）
	ActiveConnections int32                  `protobuf:"varint,3,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`                               // 活跃连接数
	Metadata          map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 额外元数据
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_upstream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_upstream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_upstream_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusResponse) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *StatusResponse) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *StatusResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 单播推送请求
type UnicastPushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetType    string                 `protobuf:"bytes,1,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`                                                     // 目标类型: session, gid, openid
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`                                                           // 目标标识符
	MsgType       string                 `protobuf:"bytes,3,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`                                                              // 消息类型
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`                                                                                 // 推送标题
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                                                                             // 推送内容
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`                                                                                   // 额外数据
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnicastPushRequest) Reset() {
	*x = UnicastPushRequest{}
	mi := &file_upstream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnicastPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnicastPushRequest) ProtoMessage() {}

func (x *UnicastPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upstream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnicastPushRequest.ProtoReflect.Descriptor instead.
func (*UnicastPushRequest) Descriptor() ([]byte, []int) {
	return file_upstream_proto_rawDescGZIP(), []int{4}
}

func (x *UnicastPushRequest) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *UnicastPushRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *UnicastPushRequest) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *UnicastPushRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UnicastPushRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UnicastPushRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UnicastPushRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 单播推送响应
type UnicastPushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                     // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                      // 响应消息
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // 错误代码（如果有）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnicastPushResponse) Reset() {
	*x = UnicastPushResponse{}
	mi := &file_upstream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnicastPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnicastPushResponse) ProtoMessage() {}

func (x *UnicastPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_upstream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnicastPushResponse.ProtoReflect.Descriptor instead.
func (*UnicastPushResponse) Descriptor() ([]byte, []int) {
	return file_upstream_proto_rawDescGZIP(), []int{5}
}

func (x *UnicastPushResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnicastPushResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UnicastPushResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

// 批量单播推送请求
type BatchUnicastPushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []*UnicastTarget       `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`                                                                             // 目标列表
	MsgType       string                 `protobuf:"bytes,2,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`                                                              // 消息类型
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                                                                                 // 推送标题
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                                                                             // 推送内容
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`                                                                                   // 额外数据
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUnicastPushRequest) Reset() {
	*x = BatchUnicastPushRequest{}
	mi := &file_upstream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUnicastPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUnicastPushRequest) ProtoMessage() {}

func (x *BatchUnicastPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upstream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUnicastPushRequest.ProtoReflect.Descriptor instead.
func (*BatchUnicastPushRequest) Descriptor() ([]byte, []int) {
	return file_upstream_proto_rawDescGZIP(), []int{6}
}

func (x *BatchUnicastPushRequest) GetTargets() []*UnicastTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *BatchUnicastPushRequest) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *BatchUnicastPushRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BatchUnicastPushRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *BatchUnicastPushRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BatchUnicastPushRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 单播目标
type UnicastTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetType    string                 `protobuf:"bytes,1,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"` // 目标类型: session, gid, openid
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`       // 目标标识符
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnicastTarget) Reset() {
	*x = UnicastTarget{}
	mi := &file_upstream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnicastTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnicastTarget) ProtoMessage() {}

func (x *UnicastTarget) ProtoReflect() protoreflect.Message {
	mi := &file_upstream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnicastTarget.ProtoReflect.Descriptor instead.
func (*UnicastTarget) Descriptor() ([]byte, []int) {
	return file_upstream_proto_rawDescGZIP(), []int{7}
}

func (x *UnicastTarget) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *UnicastTarget) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

// 批量单播推送响应
type BatchUnicastPushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount  int32                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"` // 成功数量
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`       // 总数量
	Results       []*UnicastResult       `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`                                // 详细结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUnicastPushResponse) Reset() {
	*x = BatchUnicastPushResponse{}
	mi := &file_upstream_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUnicastPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUnicastPushResponse) ProtoMessage() {}

func (x *BatchUnicastPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_upstream_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUnicastPushResponse.ProtoReflect.Descriptor instead.
func (*BatchUnicastPushResponse) Descriptor() ([]byte, []int) {
	return file_upstream_proto_rawDescGZIP(), []int{8}
}

func (x *BatchUnicastPushResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BatchUnicastPushResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *BatchUnicastPushResponse) GetResults() []*UnicastResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// 单播结果
type UnicastResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetType    string                 `protobuf:"bytes,1,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`       // 目标类型
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`             // 目标标识符
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`                              // 是否成功
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 错误信息（如果有）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnicastResult) Reset() {
	*x = UnicastResult{}
	mi := &file_upstream_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnicastResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnicastResult) ProtoMessage() {}

func (x *UnicastResult) ProtoReflect() protoreflect.Message {
	mi := &file_upstream_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnicastResult.ProtoReflect.Descriptor instead.
func (*UnicastResult) Descriptor() ([]byte, []int) {
	return file_upstream_proto_rawDescGZIP(), []int{9}
}

func (x *UnicastResult) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *UnicastResult) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *UnicastResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnicastResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_upstream_proto protoreflect.FileDescriptor

const file_upstream_proto_rawDesc = "" +
	"\n" +
	"\x0eupstream.proto\x12\rgatesvr.proto\"\x9a\x03\n" +
	"\x0fUpstreamRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06openid\x18\x02 \x01(\tR\x06openid\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12B\n" +
	"\x06params\x18\x04 \x03(\v2*.gatesvr.proto.UpstreamRequest.ParamsEntryR\x06params\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12E\n" +
	"\aheaders\x18\x06 \x03(\v2+.gatesvr.proto.UpstreamRequest.HeadersEntryR\aheaders\x12\"\n" +
	"\rclient_seq_id\x18\a \x01(\x04R\vclientSeqId\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x02\n" +
	"\x10UpstreamResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12F\n" +
	"\aheaders\x18\x04 \x03(\v2,.gatesvr.proto.UpstreamResponse.HeadersEntryR\aheaders\x12\"\n" +
	"\rclient_seq_id\x18\x05 \x01(\x04R\vclientSeqId\x12\"\n" +
	"\rserver_seq_id\x18\x06 \x01(\x04R\vserverSeqId\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"2\n" +
	"\rStatusRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"\xf5\x01\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06uptime\x18\x02 \x01(\x03R\x06uptime\x12-\n" +
	"\x12active_connections\x18\x03 \x01(\x05R\x11activeConnections\x12G\n" +
	"\bmetadata\x18\x04 \x03(\v2+.gatesvr.proto.StatusResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbb\x02\n" +
	"\x12UnicastPushRequest\x12\x1f\n" +
	"\vtarget_type\x18\x01 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x19\n" +
	"\bmsg_type\x18\x03 \x01(\tR\amsgType\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12K\n" +
	"\bmetadata\x18\a \x03(\v2/.gatesvr.proto.UnicastPushRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"h\n" +
	"\x13UnicastPushResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\"\xbf\x02\n" +
	"\x17BatchUnicastPushRequest\x126\n" +
	"\atargets\x18\x01 \x03(\v2\x1c.gatesvr.proto.UnicastTargetR\atargets\x12\x19\n" +
	"\bmsg_type\x18\x02 \x01(\tR\amsgType\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12P\n" +
	"\bmetadata\x18\x06 \x03(\v24.gatesvr.proto.BatchUnicastPushRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\rUnicastTarget\x12\x1f\n" +
	"\vtarget_type\x18\x01 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\"\x98\x01\n" +
	"\x18BatchUnicastPushResponse\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x05R\fsuccessCount\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x126\n" +
	"\aresults\x18\x03 \x03(\v2\x1c.gatesvr.proto.UnicastResultR\aresults\"\x8c\x01\n" +
	"\rUnicastResult\x12\x1f\n" +
	"\vtarget_type\x18\x01 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage2\xae\x01\n" +
	"\x0fUpstreamService\x12Q\n" +
	"\x0eProcessRequest\x12\x1e.gatesvr.proto.UpstreamRequest\x1a\x1f.gatesvr.proto.UpstreamResponse\x12H\n" +
	"\tGetStatus\x12\x1c.gatesvr.proto.StatusRequest\x1a\x1d.gatesvr.proto.StatusResponse2\xce\x01\n" +
	"\x0eGatewayService\x12U\n" +
	"\fPushToClient\x12!.gatesvr.proto.UnicastPushRequest\x1a\".gatesvr.proto.UnicastPushResponse\x12e\n" +
	"\x12BatchPushToClients\x12&.gatesvr.proto.BatchUnicastPushRequest\x1a'.gatesvr.proto.BatchUnicastPushResponseB\x0fZ\rgatesvr/protob\x06proto3"

var (
	file_upstream_proto_rawDescOnce sync.Once
	file_upstream_proto_rawDescData []byte
)

func file_upstream_proto_rawDescGZIP() []byte {
	file_upstream_proto_rawDescOnce.Do(func() {
		file_upstream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_upstream_proto_rawDesc), len(file_upstream_proto_rawDesc)))
	})
	return file_upstream_proto_rawDescData
}

var file_upstream_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_upstream_proto_goTypes = []any{
	(*UpstreamRequest)(nil),          // 0: gatesvr.proto.UpstreamRequest
	(*UpstreamResponse)(nil),         // 1: gatesvr.proto.UpstreamResponse
	(*StatusRequest)(nil),            // 2: gatesvr.proto.StatusRequest
	(*StatusResponse)(nil),           // 3: gatesvr.proto.StatusResponse
	(*UnicastPushRequest)(nil),       // 4: gatesvr.proto.UnicastPushRequest
	(*UnicastPushResponse)(nil),      // 5: gatesvr.proto.UnicastPushResponse
	(*BatchUnicastPushRequest)(nil),  // 6: gatesvr.proto.BatchUnicastPushRequest
	(*UnicastTarget)(nil),            // 7: gatesvr.proto.UnicastTarget
	(*BatchUnicastPushResponse)(nil), // 8: gatesvr.proto.BatchUnicastPushResponse
	(*UnicastResult)(nil),            // 9: gatesvr.proto.UnicastResult
	nil,                              // 10: gatesvr.proto.UpstreamRequest.ParamsEntry
	nil,                              // 11: gatesvr.proto.UpstreamRequest.HeadersEntry
	nil,                              // 12: gatesvr.proto.UpstreamResponse.HeadersEntry
	nil,                              // 13: gatesvr.proto.StatusResponse.MetadataEntry
	nil,                              // 14: gatesvr.proto.UnicastPushRequest.MetadataEntry
	nil,                              // 15: gatesvr.proto.BatchUnicastPushRequest.MetadataEntry
}
var file_upstream_proto_depIdxs = []int32{
	10, // 0: gatesvr.proto.UpstreamRequest.params:type_name -> gatesvr.proto.UpstreamRequest.ParamsEntry
	11, // 1: gatesvr.proto.UpstreamRequest.headers:type_name -> gatesvr.proto.UpstreamRequest.HeadersEntry
	12, // 2: gatesvr.proto.UpstreamResponse.headers:type_name -> gatesvr.proto.UpstreamResponse.HeadersEntry
	13, // 3: gatesvr.proto.StatusResponse.metadata:type_name -> gatesvr.proto.StatusResponse.MetadataEntry
	14, // 4: gatesvr.proto.UnicastPushRequest.metadata:type_name -> gatesvr.proto.UnicastPushRequest.MetadataEntry
	7,  // 5: gatesvr.proto.BatchUnicastPushRequest.targets:type_name -> gatesvr.proto.UnicastTarget
	15, // 6: gatesvr.proto.BatchUnicastPushRequest.metadata:type_name -> gatesvr.proto.BatchUnicastPushRequest.MetadataEntry
	9,  // 7: gatesvr.proto.BatchUnicastPushResponse.results:type_name -> gatesvr.proto.UnicastResult
	0,  // 8: gatesvr.proto.UpstreamService.ProcessRequest:input_type -> gatesvr.proto.UpstreamRequest
	2,  // 9: gatesvr.proto.UpstreamService.GetStatus:input_type -> gatesvr.proto.StatusRequest
	4,  // 10: gatesvr.proto.GatewayService.PushToClient:input_type -> gatesvr.proto.UnicastPushRequest
	6,  // 11: gatesvr.proto.GatewayService.BatchPushToClients:input_type -> gatesvr.proto.BatchUnicastPushRequest
	1,  // 12: gatesvr.proto.UpstreamService.ProcessRequest:output_type -> gatesvr.proto.UpstreamResponse
	3,  // 13: gatesvr.proto.UpstreamService.GetStatus:output_type -> gatesvr.proto.StatusResponse
	5,  // 14: gatesvr.proto.GatewayService.PushToClient:output_type -> gatesvr.proto.UnicastPushResponse
	8,  // 15: gatesvr.proto.GatewayService.BatchPushToClients:output_type -> gatesvr.proto.BatchUnicastPushResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_upstream_proto_init() }
func file_upstream_proto_init() {
	if File_upstream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_upstream_proto_rawDesc), len(file_upstream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_upstream_proto_goTypes,
		DependencyIndexes: file_upstream_proto_depIdxs,
		MessageInfos:      file_upstream_proto_msgTypes,
	}.Build()
	File_upstream_proto = out.File
	file_upstream_proto_goTypes = nil
	file_upstream_proto_depIdxs = nil
}
